training:
  lr: 0.001
  n_epochs: 100
general:
  n_experts: 2
  expert_type: resnet50
  print_every: 100
dataset:
  cub200:
    n_classes: 200
    input_dim: null
    batch_size: 8
  mnist:
    n_classes: 10
    input_dim: 784
    batch_size: 64
  cifar10:
    n_classes: 10
    input_dim: null
    batch_size: 64
nets:
  resnet18:
    emb_dim: 512
